Algoritmo "faccat44"
// Disciplina   : [ Lógica de Programação]
// Professor   : Jailson Costa 
// Descrição   : Efetuar a divisão de um valor!
// Autor(a)    : Bernardo Prieto
// Data atual  : 06/10/2023
Var
valorA,valorB:inteiro


Inicio
escreval("Informe o primeiro valor")
leia(valorA)
repita
escreval("Informe o segundo valor")
leia(valorB)
ate valorB <> 0
Escreval("A divisão do primeiro pelo segundo valor é ", valorA/valorB)



Fimalgoritmo