Algoritmo "faccat54"
// Disciplina   : [ Lógica de Programação]
// Professor   : Jailson Costa 
// Descrição   : Contadora de 1 até um número informado pelo usuário
//               o valor informado nã pode ser menor do que 0!
// Autor(a)    : Bernardo Prieto
// Data atual  : 08/10/2023
Var
contadora,numero:inteiro

Inicio
repita
escreval("Informe um número")
leia(numero)
ate numero > 0
para contadora de 1 ate numero passo 1 faca
escreval(contadora)
fimpara


Fimalgoritmo