Algoritmo "faccat56"
// Disciplina   : [ Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Tabuada de qualquer número informado pelo usuário!
// Autor(a)    : Bernardo Prieto
// Data atual  : 08/10/2023
Var
contadora,numero,tabuada:inteiro


Inicio
escreval("Informe um valor!")
leia(numero)
para contadora de 1 ate 10 passo 1 faca
tabuada<-numero*contadora
escreval(numero," X ",contadora," = ",tabuada)
fimpara



Fimalgoritmo